[params.plausible]
   enable = true
   domain = "sutasoma.eth.link"
   outbound_link = true
   # Manage Adblockers
   # custom_js_domain = "stats.mydomain.org"   # Deprecated -> please use proxying
   proxy_netlify = false
   # Self hosting
   # selfhosted_domain = "myownplausible.mydomain.org"
   # Write public dashboard url in source
   public_dashboard = true
   # For embeded dashboard
   dash_disable = false
   dash_link = "https://plausible.io/share/sutasoma.eth.link?auth=fPFBWdhVUXTdgh8PBcsED"
   dash_theme = "dark"
   dash_bgcolor = "#880011"
   # debug mode
   debug = true
[params.plausible_version]
   id = "1.13.0"
